### ISSUE TITLE
Event with less than 1 hour duration are merged with different end times

### ISSUE THREAD

**Issue by patrickkusebauch** [imightbeamy/gcal-multical-event-merge#56] opened 2018-02-19 11:37 UTC
In the new version for the new Google UI event are merged if the follow these conditions:
- Same name
- Same start time
- Different end time

Expected behavior: Events are merged **if and only if** they also have the same end time

**Comment by imightbeamy** [comment] 2018-02-19 14:18
Hmm, I'm not able to reproduce this exactly, events with different end times are not being merged:
![screen shot 2018-02-19 at 9 12 30 am](https://user-images.githubusercontent.com/1229145/36381904-10fa9a88-1555-11e8-9c22-b441ffc6b602.png)![screen shot 2018-02-19 at 9 12 44 am](https://user-images.githubusercontent.com/1229145/36381903-10bafa22-1555-11e8-9ba2-a91d806cc3f4.png)

The only time I see something kind of like this is if I change the duration of on event. When I do that one of them stays merged:
![feb-19-2018 09-15-38](https://user-images.githubusercontent.com/1229145/36381996-78f9f73c-1555-11e8-81bd-6f6fa474bbf3.gif)

Is that what you're seeing?

If not, can you add some screenshots of events that are merging incorrectly for you? Please include one with the extension on and off. Thanks!

**Comment by imightbeamy** [comment] 2018-02-21 04:21
I've uploaded [a new release](https://github.com/imightbeamy/gcal-multical-event-merge/releases/tag/v2.1.2) that fixed the behavior in my gif, if that's not the problem you're seeing let me know.

**Comment by patrickkusebauch** [comment] 2018-02-21 12:33
Hello, finally got the time to write a reproducible steps:

- Create event 1 (say 10:00 to 10:45 - 45 minutes)
- Create event 2 (say 11:00 to 11:30 - 30 minutes) with same name as event 1 in different calendar
- Move event 2 to start at 10:00 (now lasts from 10:00 to 10:30)

**Unexpected behavior:** Events are merged
**Expected behavior:** Events are not merged

**Comment by imightbeamy** [comment] 2018-02-21 13:57
Ah! I see it seems to happen only when both events are < 1 hour. How weird! 

With < 1 hour:


With > 1 hour:
![feb-21-2018 08-53-17](https://user-images.githubusercontent.com/1229145/36483813-3252d5f6-16e5-11e8-8dda-0b260078aa5d.gif)

**Comment by Hadriel** [comment] 2018-02-21 17:27
Could this be because events with less than 1h duration don't have the end time in the description text?

**Comment by imightbeamy** [comment] 2018-02-21 21:44
Ooh I bet that's it @Hadriel! Maybe we could add the top/bottom value from the event bounding box to the key 🤔

**Comment by manuelmeister** [comment] 2022-07-01 08:09
Was everything fixed with the PR by @Hadriel?

**Closed** 2024-01-30 17:52 UTC
Labels: bug, help wanted
